<div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
   <h1 class="page-header">Home</h1>
   <div class="row">
      <?php if (count($this->view->contact) > 0) : ?>
         <table class="table table-striped table-bordered table-hover">
            <thead>
               <tr>
                  <td>Nome</td>
                  <td>Celular</td>
                  <td>Fixo</td>
                  <td>Email</td>
               </tr>
            </thead>
            <tbody>
               <?php foreach ($this->view->contact as $contact): ?>
                  <tr>
                     <td><?php echo $contact->name ?></td>
                     <td><?php echo $contact->cell_number ?></td>
                     <td><?php echo $contact->phone_number ?></td>
                     <td><?php echo $contact->email ?></td>
                  </tr>
               <?php endforeach; ?>
            </tbody>
         </table>
      <?php else: ?>
         <p class="btn-warning">Nenhum registro encontrado.</p>
      <?php endif; ?>
   </div>
</div>

<script src="<?php echo URL_SITE; ?>/js/home/index.js" type="text/javascript"></script>