<div class="col-sm-9 col-sm-offset-2 col-md-10 col-md-offset-1 main">
   <h1 class="page-header">Contato(s)</h1>
   <div class="col-sm-12 btn-cad">
      <a href="<?php echo URL_SITE; ?>/contact/create" class="btn btn-success btn-lg active" role="button">Cadastrar</a>
   </div>
   <div class="row frm-pesq">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h4>Pesquisar</h4>
         </div>
         <div class="panel-body">
            <form class="form-horizontal" action="#" method="GET" id="frm-pesquisar" url="<?php echo URL_SITE ?>">
               <div class="col-sm-6">
                  <div class="form-group">
                     <label class="col-sm-4 control-label" for="name">Nome</label>
                     <div class="col-sm-6">
                        <input id="name" name="name" placeholder="Nome" class="form-control input-md" 
                               type="text" value="<?php echo $_GET['name'] ?>"> 
                     </div>
                  </div>
               </div>
               <div class="col-sm-6">
                  <div class="form-group">
                     <label class="col-sm-4 control-label" for="email">Email</label>
                     <div class="col-sm-6">
                        <input id="email" name="email" placeholder="email@.com.br" class="form-control input-md"
                              type="text" value="<?php echo $_GET['email'] ?>">
                     </div>
                  </div>
               </div>
               <div class="col-sm-6">
                  <div class="form-group">
                     <label class="col-sm-4 control-label" for="cell_number">Celular</label>
                     <div class="col-sm-6">
                        <input id="cell_number" name="cell_number" placeholder="(99) 9 9999-9999" 
                               class="form-control input-md" type="text" value="<?php echo $_GET['cell_number'] ?>">
                     </div>
                  </div>
               </div>
               <div class="col-sm-6"><!-- Text input-->
                  <div class="form-group">
                     <label class="col-sm-4 control-label" for="phone_number">Telefone Fixo</label>
                     <div class="col-sm-6">
                        <input id="phone_number" name="phone_number" placeholder="(99) 9 9999-9999" 
                              class="form-control input-md" type="text" value="<?php echo $_GET['phone_number'] ?>">
                     </div>
                  </div>
               </div>
            </form>
         </div>
         <div class="panel-footer">
            <div class="btn-group col-md-offset-5">
               <div class="col-sm-12">
                  <button type="button" id="submit" class="btn btn-primary">Pesquisar</button>
               </div>
            </div>
         </div>
      </div>   

      <hr>
      <?php if (count($this->view->contact) > 0) : ?>
         <table class="table table-striped table-bordered table-hover">
            <thead>
               <tr>
                  <td>Nome</td>
                  <td>Celular</td>
                  <td>Fixo</td>
                  <td>Email</td>
                  <td>Opções</td>
               </tr>
            </thead>
            <tbody>
               <?php foreach ($this->view->contact as $contact): ?>
                  <tr>
                     <td><?php echo $contact->name ?></td>
                     <td><?php echo $contact->cell_number ?></td>
                     <td><?php echo $contact->phone_number ?></td>
                     <td><?php echo $contact->email ?></td>
                     <td>
                        <button type="button" val="<?php echo $contact->id ?>" class="btn btn-default fa fa-edit edit" 
                           data-toggle="tooltip" data-placement="top" title="Editar Contato">
                        </button>
                        <button type="button" val="<?php echo $contact->id ?>" class="btn btn-default fa fa-minus-circle remove"
                           data-toggle="tooltip" data-placement="top" title="Excluir Contato" >
                        </button>
                     </td>
                  </tr>
               <?php endforeach; ?>
            </tbody>
         </table>
      <?php else: ?>
         <p class="btn-warning">Nenhum registro encontrado.</p>
      <?php endif; ?>
   </div>
</div>

<script src="<?php echo URL_SITE; ?>/js/contact/index.js" type="text/javascript"></script>