<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>Agenda Telefônica</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css"> 
      <link rel="stylesheet" href="<?php echo URL_SITE; ?>/css/styles.css">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <script src="<?php echo URL_SITE; ?>/js/lib/jqueryMask/jquery.mask.js"></script>
   </head>
   <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
         <div class="container-fluid">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
               </button>
               <a href="<?php echo URL_SITE; ?>" class="navbar-brand">Agenda Telefônica</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
               <!--<ul class="nav navbar-nav navbar-right">-->
                  <ul class="nav navbar-nav">   
                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Contatos <span class="caret"></span>
                     </a>
                     <ul class="dropdown-menu">
                        <li><a href="/contact/index">Listar</a></li>
                        <!--<li><a href="/contact/create">Novo</a></li>-->
                     </ul>
                  </li>
<!--                  <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Usuários <span class="caret"></span>
                     </a>
                     <ul class="dropdown-menu">
                        <li><a href="/use/index">Listar</a></li>
                        <li><a href="/user/create">Novo</a></li>
                     </ul>
                  </li>-->
               </ul>
            </div>
         </div>
      </nav>

      <div class="container-fluid">
         <?php echo $this->content() ?>
      </div>
   </div>
   <hr>
   <footer class="container">
      <p>&copy;2018 - Carlos Henrique Lavezo</p>
   </footer>
</body>
</html>